import { WorkspaceFile } from '@/types/workspace';
import JSZip from 'jszip';

export interface DeploymentGuide {
  platform: 'Vercel' | 'Netlify' | 'Cloudflare';
  title: string;
  steps: string[];
}

export interface ExportBundle {
  projectName: string;
  files: WorkspaceFile[];
  readmeContent: string;
  envExampleContent: string;
  deploymentGuides: DeploymentGuide[];
}

export class ProjectExporter {
  /**
   * Scrubs API keys and secrets before exporting project files
   */
  private static sanitizeFileForExport(content: string): string {
    return content
      .replace(/sk-[a-zA-Z0-9]{20,}/g, 'YOUR_API_KEY_HERE')
      .replace(/sb_secret_[a-zA-Z0-9_]+/g, 'YOUR_SUPABASE_SECRET_HERE')
      .replace(/eyJ[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+\.[a-zA-Z0-9_-]+/g, 'YOUR_TOKEN_HERE');
  }

  /**
   * Generates a complete export bundle with README and Deployment Guides
   */
  static generateExportBundle(params: {
    projectName: string;
    description?: string;
    files: WorkspaceFile[];
  }): ExportBundle {
    const cleanFiles = params.files.map((f) => ({
      ...f,
      file_content: this.sanitizeFileForExport(f.file_content),
    }));

    const readmeContent = `
# ${params.projectName}

${params.description || 'Built with MAXCES AI OS — Autonomous AI Operating System'}

## 🚀 Quick Start Guide

1. Clone or extract this repository.
2. Install project dependencies:
   \`\`\`bash
   npm install
   \`\`\`
3. Copy environment settings:
   \`\`\`bash
   cp .env.example .env.local
   \`\`\`
4. Launch local dev server:
   \`\`\`bash
   npm run dev
   \`\`\`

## 🛠️ Built With
- React 19 + TypeScript
- Vite 8 Engine
- Tailwind CSS v4
- Supabase Cloud Database & Auth

---
*Generated by MAXCES AI OS*
`.trim();

    const envExampleContent = `
# MAXCES AI OS — Environment Configuration
VITE_SUPABASE_URL=https://your-project.supabase.co
VITE_SUPABASE_ANON_KEY=your-supabase-anon-key
VITE_GEMINI_API_KEY=your-gemini-api-key
`.trim();

    const deploymentGuides: DeploymentGuide[] = [
      {
        platform: 'Vercel',
        title: 'Deploying to Vercel (1-Click Hosting)',
        steps: [
          'Push code to your GitHub repository.',
          'Log in to Vercel.com and click "Add New Project".',
          'Import your GitHub repository.',
          'Add VITE_SUPABASE_URL and VITE_SUPABASE_ANON_KEY in Environment Variables.',
          'Click "Deploy" — Vercel will build your site in ~30 seconds.',
        ],
      },
      {
        platform: 'Netlify',
        title: 'Deploying to Netlify',
        steps: [
          'Connect your GitHub repository to Netlify.com.',
          'Set Build Command to `npm run build` and Publish Directory to `dist`.',
          'Add environment variables in Site Configuration.',
          'Click "Deploy Site".',
        ],
      },
      {
        platform: 'Cloudflare',
        title: 'Deploying to Cloudflare Workers / Pages',
        steps: [
          'Install Wrangler CLI or connect repository in Cloudflare Dashboard.',
          'Set framework preset to Vite / React.',
          'Deploy instantly to global edge servers.',
        ],
      },
    ];

    return {
      projectName: params.projectName,
      files: cleanFiles,
      readmeContent,
      envExampleContent,
      deploymentGuides,
    };
  }

  /**
   * Generates and triggers 1-Click ZIP project download
   */
  static async downloadZipBundle(params: {
    projectName: string;
    files: WorkspaceFile[];
  }): Promise<boolean> {
    try {
      const bundle = this.generateExportBundle({
        projectName: params.projectName,
        files: params.files,
      });

      const zip = new JSZip();

      // 1. Add all virtual workspace files preserving directory structure
      bundle.files.forEach((file) => {
        zip.file(file.file_path, file.file_content);
      });

      // 2. Automatically include README.md if missing
      if (!zip.file('README.md')) {
        zip.file('README.md', bundle.readmeContent);
      }

      // 3. Automatically include .env.example
      if (!zip.file('.env.example')) {
        zip.file('.env.example', bundle.envExampleContent);
      }

      // 4. Automatically include .gitignore
      if (!zip.file('.gitignore')) {
        zip.file(
          '.gitignore',
          `node_modules\n.env.local\ndist\n.output\n.wrangler\n.DS_Store\n`
        );
      }

      // 5. Automatically include package.json if missing
      if (!zip.file('package.json')) {
        const defaultPackageJson = JSON.stringify(
          {
            name: params.projectName.toLowerCase().replace(/[^a-z0-9_-]/g, '-'),
            private: true,
            version: '1.0.0',
            type: 'module',
            scripts: {
              dev: 'vite',
              build: 'tsc && vite build',
              preview: 'vite preview',
            },
            dependencies: {
              react: '^19.0.0',
              'react-dom': '^19.0.0',
              'lucide-react': '^0.460.0',
            },
            devDependencies: {
              '@vitejs/plugin-react': '^4.3.0',
              typescript: '^5.6.0',
              vite: '^5.4.0',
            },
          },
          null,
          2
        );
        zip.file('package.json', defaultPackageJson);
      }

      // 6. Generate ZIP Blob and trigger 1-click browser download
      const blob = await zip.generateAsync({ type: 'blob' });
      const downloadUrl = URL.createObjectURL(blob);
      const link = document.createElement('a');
      link.href = downloadUrl;
      link.download = `${params.projectName.toLowerCase().replace(/[^a-z0-9_-]/g, '-')}.zip`;
      document.body.appendChild(link);
      link.click();
      document.body.removeChild(link);
      URL.revokeObjectURL(downloadUrl);

      return true;
    } catch (err) {
      console.error('[ProjectExporter.downloadZipBundle Error]:', err);
      return false;
    }
  }
}
