/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppWebsiteReviewRouteImport } from './routes/_app.website-review'
import { Route as AppUiReviewRouteImport } from './routes/_app.ui-review'
import { Route as AppTimelineRouteImport } from './routes/_app.timeline'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppResearchRouteImport } from './routes/_app.research'
import { Route as AppPromptStudioRouteImport } from './routes/_app.prompt-studio'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppProfileRouteImport } from './routes/_app.profile'
import { Route as AppMemoryRouteImport } from './routes/_app.memory'
import { Route as AppFilesRouteImport } from './routes/_app.files'
import { Route as AppCodeBuilderRouteImport } from './routes/_app.code-builder'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppBusinessRouteImport } from './routes/_app.business'
import { Route as AppAnalyticsRouteImport } from './routes/_app.analytics'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppWebsiteReviewRoute = AppWebsiteReviewRouteImport.update({
  id: '/website-review',
  path: '/website-review',
  getParentRoute: () => AppRoute,
} as any)
const AppUiReviewRoute = AppUiReviewRouteImport.update({
  id: '/ui-review',
  path: '/ui-review',
  getParentRoute: () => AppRoute,
} as any)
const AppTimelineRoute = AppTimelineRouteImport.update({
  id: '/timeline',
  path: '/timeline',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppResearchRoute = AppResearchRouteImport.update({
  id: '/research',
  path: '/research',
  getParentRoute: () => AppRoute,
} as any)
const AppPromptStudioRoute = AppPromptStudioRouteImport.update({
  id: '/prompt-studio',
  path: '/prompt-studio',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppProfileRoute = AppProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => AppRoute,
} as any)
const AppMemoryRoute = AppMemoryRouteImport.update({
  id: '/memory',
  path: '/memory',
  getParentRoute: () => AppRoute,
} as any)
const AppFilesRoute = AppFilesRouteImport.update({
  id: '/files',
  path: '/files',
  getParentRoute: () => AppRoute,
} as any)
const AppCodeBuilderRoute = AppCodeBuilderRouteImport.update({
  id: '/code-builder',
  path: '/code-builder',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppBusinessRoute = AppBusinessRouteImport.update({
  id: '/business',
  path: '/business',
  getParentRoute: () => AppRoute,
} as any)
const AppAnalyticsRoute = AppAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/analytics': typeof AppAnalyticsRoute
  '/business': typeof AppBusinessRoute
  '/chat': typeof AppChatRoute
  '/code-builder': typeof AppCodeBuilderRoute
  '/files': typeof AppFilesRoute
  '/memory': typeof AppMemoryRoute
  '/profile': typeof AppProfileRoute
  '/projects': typeof AppProjectsRoute
  '/prompt-studio': typeof AppPromptStudioRoute
  '/research': typeof AppResearchRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/timeline': typeof AppTimelineRoute
  '/ui-review': typeof AppUiReviewRoute
  '/website-review': typeof AppWebsiteReviewRoute
}
export interface FileRoutesByTo {
  '/analytics': typeof AppAnalyticsRoute
  '/business': typeof AppBusinessRoute
  '/chat': typeof AppChatRoute
  '/code-builder': typeof AppCodeBuilderRoute
  '/files': typeof AppFilesRoute
  '/memory': typeof AppMemoryRoute
  '/profile': typeof AppProfileRoute
  '/projects': typeof AppProjectsRoute
  '/prompt-studio': typeof AppPromptStudioRoute
  '/research': typeof AppResearchRoute
  '/settings': typeof AppSettingsRoute
  '/tasks': typeof AppTasksRoute
  '/timeline': typeof AppTimelineRoute
  '/ui-review': typeof AppUiReviewRoute
  '/website-review': typeof AppWebsiteReviewRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/analytics': typeof AppAnalyticsRoute
  '/_app/business': typeof AppBusinessRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/code-builder': typeof AppCodeBuilderRoute
  '/_app/files': typeof AppFilesRoute
  '/_app/memory': typeof AppMemoryRoute
  '/_app/profile': typeof AppProfileRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/prompt-studio': typeof AppPromptStudioRoute
  '/_app/research': typeof AppResearchRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/timeline': typeof AppTimelineRoute
  '/_app/ui-review': typeof AppUiReviewRoute
  '/_app/website-review': typeof AppWebsiteReviewRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/analytics'
    | '/business'
    | '/chat'
    | '/code-builder'
    | '/files'
    | '/memory'
    | '/profile'
    | '/projects'
    | '/prompt-studio'
    | '/research'
    | '/settings'
    | '/tasks'
    | '/timeline'
    | '/ui-review'
    | '/website-review'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/analytics'
    | '/business'
    | '/chat'
    | '/code-builder'
    | '/files'
    | '/memory'
    | '/profile'
    | '/projects'
    | '/prompt-studio'
    | '/research'
    | '/settings'
    | '/tasks'
    | '/timeline'
    | '/ui-review'
    | '/website-review'
    | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/analytics'
    | '/_app/business'
    | '/_app/chat'
    | '/_app/code-builder'
    | '/_app/files'
    | '/_app/memory'
    | '/_app/profile'
    | '/_app/projects'
    | '/_app/prompt-studio'
    | '/_app/research'
    | '/_app/settings'
    | '/_app/tasks'
    | '/_app/timeline'
    | '/_app/ui-review'
    | '/_app/website-review'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/website-review': {
      id: '/_app/website-review'
      path: '/website-review'
      fullPath: '/website-review'
      preLoaderRoute: typeof AppWebsiteReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/ui-review': {
      id: '/_app/ui-review'
      path: '/ui-review'
      fullPath: '/ui-review'
      preLoaderRoute: typeof AppUiReviewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/timeline': {
      id: '/_app/timeline'
      path: '/timeline'
      fullPath: '/timeline'
      preLoaderRoute: typeof AppTimelineRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/research': {
      id: '/_app/research'
      path: '/research'
      fullPath: '/research'
      preLoaderRoute: typeof AppResearchRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/prompt-studio': {
      id: '/_app/prompt-studio'
      path: '/prompt-studio'
      fullPath: '/prompt-studio'
      preLoaderRoute: typeof AppPromptStudioRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/profile': {
      id: '/_app/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof AppProfileRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/memory': {
      id: '/_app/memory'
      path: '/memory'
      fullPath: '/memory'
      preLoaderRoute: typeof AppMemoryRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/files': {
      id: '/_app/files'
      path: '/files'
      fullPath: '/files'
      preLoaderRoute: typeof AppFilesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/code-builder': {
      id: '/_app/code-builder'
      path: '/code-builder'
      fullPath: '/code-builder'
      preLoaderRoute: typeof AppCodeBuilderRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/business': {
      id: '/_app/business'
      path: '/business'
      fullPath: '/business'
      preLoaderRoute: typeof AppBusinessRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/analytics': {
      id: '/_app/analytics'
      path: '/analytics'
      fullPath: '/analytics'
      preLoaderRoute: typeof AppAnalyticsRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppAnalyticsRoute: typeof AppAnalyticsRoute
  AppBusinessRoute: typeof AppBusinessRoute
  AppChatRoute: typeof AppChatRoute
  AppCodeBuilderRoute: typeof AppCodeBuilderRoute
  AppFilesRoute: typeof AppFilesRoute
  AppMemoryRoute: typeof AppMemoryRoute
  AppProfileRoute: typeof AppProfileRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppPromptStudioRoute: typeof AppPromptStudioRoute
  AppResearchRoute: typeof AppResearchRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppTimelineRoute: typeof AppTimelineRoute
  AppUiReviewRoute: typeof AppUiReviewRoute
  AppWebsiteReviewRoute: typeof AppWebsiteReviewRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppAnalyticsRoute: AppAnalyticsRoute,
  AppBusinessRoute: AppBusinessRoute,
  AppChatRoute: AppChatRoute,
  AppCodeBuilderRoute: AppCodeBuilderRoute,
  AppFilesRoute: AppFilesRoute,
  AppMemoryRoute: AppMemoryRoute,
  AppProfileRoute: AppProfileRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppPromptStudioRoute: AppPromptStudioRoute,
  AppResearchRoute: AppResearchRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppTasksRoute: AppTasksRoute,
  AppTimelineRoute: AppTimelineRoute,
  AppUiReviewRoute: AppUiReviewRoute,
  AppWebsiteReviewRoute: AppWebsiteReviewRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
